// AUTHORIZATION
export const AUTHORIZATION_IS_LOADING = 'AUTHORIZATION_IS_LOADING';
export const AUTHORIZATION_SUCCESSED = 'AUTHORIZATION_SUCCESSED';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';

// SEND_REQUEST_1
export const SEND_REQUEST_1_IS_LOADING = 'SEND_REQUEST_1_IS_LOADING';
export const SEND_REQUEST_1_SUCCESSED = 'SEND_REQUEST_1_SUCCESSED';
export const SEND_REQUEST_1_FAILED = 'SEND_REQUEST_1_FAILED';

// SEND_REQUEST_2
export const SEND_REQUEST_2_IS_LOADING = 'SEND_REQUEST_2_IS_LOADING';
export const SEND_REQUEST_2_SUCCESSED = 'SEND_REQUEST_2_SUCCESSED';
export const SEND_REQUEST_2_FAILED = 'SEND_REQUEST_2_FAILED';

// SEND_REQUEST_3
export const SEND_REQUEST_3_IS_LOADING = 'SEND_REQUEST_3_IS_LOADING';
export const SEND_REQUEST_3_SUCCESSED = 'SEND_REQUEST_3_SUCCESSED';
export const SEND_REQUEST_3_FAILED = 'SEND_REQUEST_3_FAILED';

// USER_DATA
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';


//
export const SET_ORG_ID = 'SET_ORG_ID';
export const SET_ORG_INN = 'SET_ORG_INN';
export const SET_ORG_NAME = 'SET_ORG_NAME';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_BANK_BIC = 'SET_BANK_BIC';
export const SET_DOC_DATE = 'SET_DOC_DATE';
export const SET_DOC_ID = 'SET_DOC_ID';
export const SET_DOC_NUNBER = 'SET_DOC_NUNBER';
export const SET_FROM_DATE = 'SET_FROM_DATE';
export const SET_TO_DATE = 'SET_TO_DATE';
export const SET_BANK_NAME = 'SET_BANK_NAME';

