// AUTHORIZATION
export const AUTHORIZATION_IS_LOADING = 'AUTHORIZATION_IS_LOADING';
export const AUTHORIZATION_SUCCESSED = 'AUTHORIZATION_SUCCESSED';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';

// REQUEST_1_1
export const REQUEST_1_1_IS_LOADING = 'REQUEST_1_1_IS_LOADING';
export const REQUEST_1_1_SUCCESSED = 'REQUEST_1_1_SUCCESSED';
export const REQUEST_1_1_FAILED = 'REQUEST_1_1_FAILED';

// REQUEST_1_2
export const REQUEST_1_2_IS_LOADING = 'REQUEST_1_2_IS_LOADING';
export const REQUEST_1_2_SUCCESSED = 'REQUEST_1_2_SUCCESSED';
export const REQUEST_1_2_FAILED = 'REQUEST_1_2_FAILED';

// REQUEST_1_3
export const REQUEST_1_3_IS_LOADING = 'REQUEST_1_3_IS_LOADING';
export const REQUEST_1_3_SUCCESSED = 'REQUEST_1_3_SUCCESSED';
export const REQUEST_1_3_FAILED = 'REQUEST_1_3_FAILED';

// USER_DATA
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';

