// AUTHORIZATION
export const AUTHORIZATION_IS_LOADING = 'AUTHORIZATION_IS_LOADING';
export const AUTHORIZATION_SUCCESSED = 'AUTHORIZATION_SUCCESSED';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';

// USER_DATA
export const UPDATE_AUTORIZATION_DATA = 'UPDATE_AUTORIZATION_DATA';
