// REQUEST
export const INCOMING_IS_LOADING = 'INCOMING_IS_LOADING';
export const INCOMING_SUCCESSED = 'INCOMING_SUCCESSED';
export const INCOMING_FAILED = 'INCOMING_FAILED';

// DATA
export const SET_DOC_TYPES = 'SET_DOC_TYPES';


export const SET_DOC_TYPE = 'SET_DOC_TYPE';

export const REMOVE_DOC_TYPE = 'REMOVE_DOC_TYPE';
export const ADD_DOC_TYPE = 'ADD_DOC_TYPE';
