// ORGANISATIONS GET
export const ORGANISATIONS_GET_LOADING = 'ORGANISATIONS_GET_LOADING';
export const ORGANISATIONS_GET_SUCCEED = 'ORGANISATIONS_GET_SUCCEED';
export const ORGANISATIONS_GET_FAILED = 'ORGANISATIONS_GET_FAILED';

// ORGANISATIONS POST
export const ORGANISATION_POST_LOADING = 'ORGANISATION_POST_LOADING';
export const ORGANISATION_POST_SUCCEED = 'ORGANISATION_POST_SUCCEED';
export const ORGANISATION_POST_FAILED = 'ORGANISATION_POST_FAILED';

// ORGANISATIONS PUT
export const ORGANISATION_PUT_LOADING = 'ORGANISATION_PUT_LOADING';
export const ORGANISATION_PUT_SUCCEED = 'ORGANISATION_PUT_SUCCEED';
export const ORGANISATION_PUT_FAILED = 'ORGANISATION_PUT_FAILED';

// ORGANISATIONS DELETE
export const ORGANISATION_DELETE_LOADING = 'ORGANISATION_DELETE_LOADING';
export const ORGANISATION_DELETE_SUCCEED = 'ORGANISATION_DELETE_SUCCEED';
export const ORGANISATION_DELETE_FAILED = 'ORGANISATION_DELETE_FAILED';

export const SAVE_NEW_ORGANISATION = "SAVE_NEW_ORGANISATION";
export const ADD_ACCOUNT_TO_NEW_ORGANISATION = "ADD_ACCOUNT_TO_NEW_ORGANISATION";
export const REMOVE_ACCOUNT_FROM_NEW_ORGANISATION = "REMOVE_ACCOUNT_FROM_NEW_ORGANISATION";
export const UPDATE_NEW_ORGANISATION = 'UPDATE_NEW_ORGANISATION';
export const UPDATE_ACCOUNT_IN_NEW_ORGANISATION = "UPDATE_ACCOUNT_IN_NEW_ORGANISATION";

export const SELECT_ORGANISATION = 'SELECT_ORGANISATION';
export const SELECT_ACCOUNT = 'SELECT_ACCOUNT';

export const ADD_ORGANISATION_FOR_UPDATE = "ADD_ORGANISATION_FOR_UPDATE";
export const SAVE_UPDATED_ORGANISATION = "SAVE_UPDATED_ORGANISATION";
export const ADD_ACCOUNT_TO_UPDATE_ORGANISATION = "ADD_ACCOUNT_TO_UPDATE_ORGANISATION";
export const REMOVE_ACCOUNT_FROM_UPDATE_ORGANISATION = "REMOVE_ACCOUNT_FROM_UPDATE_ORGANISATION"
export const UPDATE_EXISTING_ORGANISATION = "UPDATE_EXISTING_ORGANISATION";
export const UPDATE_ACCOUNT_IN_UPDATE_ORGANISATION = "UPDATE_ACCOUNT_IN_UPDATE_ORGANISATION";