// REQUEST
export const STATMENT_REQUEST_IS_LOADING = 'STATMENT_REQUEST_IS_LOADING';
export const STATMENT_REQUEST_SUCCESSED = 'STATMENT_REQUEST_SUCCESSED';
export const STATMENT_REQUEST_FAILED = 'STATMENT_REQUEST_FAILED';

// DATA
export const SET_DOC_DATE = 'SET_DOC_DATE';
export const SET_DOC_ID = 'SET_DOC_ID';
export const SET_DOC_NUMBER = 'SET_DOC_NUMBER';

export const SET_FROM_DATE = 'SET_FROM_DATE';
export const SET_ORG_ID = 'SET_ORG_ID';
export const SET_ORG_INN = 'SET_ORG_INN';
export const SET_ORG_NAME = 'SET_ORG_NAME';
export const SET_TO_DATE = 'SET_TO_DATE';

export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_BANK_BIC = 'SET_BANK_BIC';
export const SET_BANK_NAME = 'SET_BANK_NAME';

export const REMOVE_ACC = 'REMOVE_ACC';
export const ADD_ACC = 'ADD_ACC';
