// REQUEST
export const PAY_REQUEST_IS_LOADING = 'PAY_REQUEST_IS_LOADING';
export const PAY_REQUEST_SUCCESSED = 'PAY_REQUEST_SUCCESSED';
export const PAY_REQUEST_FAILED = 'PAY_REQUEST_FAILED';

// DATA
export const PAY_REQUEST_UPDATE_DATA = 'PAY_REQUEST_UPDATE_DATA';

export const UPDATE_PAY_REQUEST_PART_DATA = 'UPDATE_PAY_REQUEST_PART_DATA';
export const REMOVE_PAY_REQUEST_PART = 'REMOVE_PAY_REQUEST_PART';
export const ADD_PAY_REQUEST_PART = 'ADD_PAY_REQUEST_PART';