// REQUEST
export const GET_REQUEST_STATUS_IS_LOADING = 'GET_REQUEST_STATUS_IS_LOADING';
export const GET_REQUEST_STATUS_SUCCESSED = 'GET_REQUEST_STATUS_SUCCESSED';
export const GET_REQUEST_STATUS_FAILED = 'GET_REQUEST_STATUS_FAILED';