// REQUEST
export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_SUCCESSED = 'REQUEST_SUCCESSED';
export const REQUEST_IS_LOADING = 'REQUEST_IS_LOADING';

export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';

