export const SOAP_MESSAGE_LIST_IS_LOADING = 'SOAP_MESSAGE_LIST_IS_LOADING';
export const SOAP_MESSAGE_LIST_SUCCESSED = 'SOAP_MESSAGE_LIST_SUCCESSED';
export const SOAP_MESSAGE_LIST_FAILED = 'SOAP_MESSAGE_LIST_FAILED';