// REQUEST_LIST
export const REQUEST_LIST_IS_LOADING = 'REQUEST_LIST_IS_LOADING';
export const REQUEST_LIST_SUCCESSED = 'REQUEST_LIST_SUCCESSED';
export const REQUEST_LIST_FAILED = 'REQUEST_LIST_FAILED';



