// REQUEST_LIST
export const REQUEST_LIST_IS_LOADING = 'REQUEST_LIST_IS_LOADING';
export const REQUEST_LIST_SUCCESSED = 'REQUEST_LIST_SUCCESSED';
export const REQUEST_LIST_FAILED = 'REQUEST_LIST_FAILED';

// DATA
export const SET_DOC_TYPES = 'SET_DOC_TYPES';
export const SET_DOC_TYPE = 'SET_DOC_TYPE';
export const REMOVE_DOC_TYPE = 'REMOVE_DOC_TYPE';
export const ADD_DOC_TYPE = 'ADD_DOC_TYPE';

// REQUEST
export const NEXT_STEP_IS_LOADING = 'NEXT_STEP_IS_LOADING';
export const NEXT_STEP_SUCCESSED = 'NEXT_STEP_SUCCESSED';
export const NEXT_STEP_FAILED = 'NEXT_STEP_FAILED';



