// REQUEST
export const STATMENT_REQUEST_IS_LOADING = 'STATMENT_REQUEST_IS_LOADING';
export const STATMENT_REQUEST_SUCCESSED = 'STATMENT_REQUEST_SUCCESSED';
export const STATMENT_REQUEST_FAILED = 'STATMENT_REQUEST_FAILED';

// DATA
export const STATMENT_REQUEST_UPDATE_DATA = 'STATMENT_REQUEST_UPDATE_DATA';

export const UPDATE_ACCOUNT_DATA = 'UPDATE_ACCOUNT_DATA';
export const FILTER_ACCOUNTS = 'FILTER_ACCOUNTS';
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
